version: '3'
services:
  taigabot:
    image: sopitz/taigabot
    #build: .
    deploy:
      replicas: 0
      restart_policy:
        condition: none
    env_file:
      - ./bot.env
      - ./taiga.env
