version: '3'
services:
  taigabot:
    #image: sameersbn/postgresql:9.6-2
    build: .
    deploy:
      replicas: 0
      restart_policy:
        condition: none
    environment:
      - BOT_ID=U4EKJCASV
      - SLACK_BOT_TOKEN=xoxb-150664418913-2jhmYoo9AX831WbcQMwdByYc
